"""Initial migration for new ERD schema

Revision ID: 1f75cce15315
Revises: 
Create Date: 2026-06-10 22:32:19.344583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f75cce15315'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('no_hp', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('admin_id')
    )
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_email'), ['email'], unique=True)

    op.create_table('kategori',
    sa.Column('kategori_id', sa.Integer(), nullable=False),
    sa.Column('nama_kategori', sa.String(length=100), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('kategori_id')
    )
    op.create_table('pelanggan',
    sa.Column('pelanggan_id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('no_hp', sa.String(length=20), nullable=True),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('pelanggan_id')
    )
    with op.batch_alter_table('pelanggan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pelanggan_email'), ['email'], unique=True)

    op.create_table('barang',
    sa.Column('barang_id', sa.Integer(), nullable=False),
    sa.Column('kategori_id', sa.Integer(), nullable=False),
    sa.Column('nama_barang', sa.String(length=150), nullable=False),
    sa.Column('harga', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stok', sa.Integer(), nullable=True),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['kategori_id'], ['kategori.kategori_id'], ),
    sa.PrimaryKeyConstraint('barang_id')
    )
    op.create_table('laporan',
    sa.Column('laporan_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=True),
    sa.Column('total_transaksi', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.admin_id'], ),
    sa.PrimaryKeyConstraint('laporan_id')
    )
    op.create_table('pesanan',
    sa.Column('pesanan_id', sa.Integer(), nullable=False),
    sa.Column('pelanggan_id', sa.Integer(), nullable=False),
    sa.Column('tanggal_pesanan', sa.Date(), nullable=True),
    sa.Column('total_harga', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status_pesanan', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['pelanggan_id'], ['pelanggan.pelanggan_id'], ),
    sa.PrimaryKeyConstraint('pesanan_id')
    )
    op.create_table('detail_pesanan',
    sa.Column('detail_id', sa.Integer(), nullable=False),
    sa.Column('pesanan_id', sa.Integer(), nullable=False),
    sa.Column('barang_id', sa.Integer(), nullable=False),
    sa.Column('jumlah', sa.Integer(), nullable=False),
    sa.Column('harga', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['barang_id'], ['barang.barang_id'], ),
    sa.ForeignKeyConstraint(['pesanan_id'], ['pesanan.pesanan_id'], ),
    sa.PrimaryKeyConstraint('detail_id')
    )
    op.create_table('jadwal',
    sa.Column('jadwal_id', sa.Integer(), nullable=False),
    sa.Column('barang_id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('jam_mulai', sa.Time(), nullable=False),
    sa.Column('jam_selesai', sa.Time(), nullable=False),
    sa.Column('status_ketersediaan', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['barang_id'], ['barang.barang_id'], ),
    sa.PrimaryKeyConstraint('jadwal_id')
    )
    op.create_table('pembayaran',
    sa.Column('pembayaran_id', sa.Integer(), nullable=False),
    sa.Column('pesanan_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('tanggal_pembayaran', sa.Date(), nullable=True),
    sa.Column('metode_pembayaran', sa.String(length=50), nullable=True),
    sa.Column('bukti_pembayaran', sa.Text(), nullable=True),
    sa.Column('status_pembayaran', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.admin_id'], ),
    sa.ForeignKeyConstraint(['pesanan_id'], ['pesanan.pesanan_id'], ),
    sa.PrimaryKeyConstraint('pembayaran_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pembayaran')
    op.drop_table('jadwal')
    op.drop_table('detail_pesanan')
    op.drop_table('pesanan')
    op.drop_table('laporan')
    op.drop_table('barang')
    with op.batch_alter_table('pelanggan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pelanggan_email'))

    op.drop_table('pelanggan')
    op.drop_table('kategori')
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_email'))

    op.drop_table('admin')
    # ### end Alembic commands ###
