"""add site_setting table

Revision ID: bd62551e5bab
Revises: 1f75cce15315
Create Date: 2026-07-22 03:08:19.260780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd62551e5bab'
down_revision = '1f75cce15315'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('site_setting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_site_setting_key'), ['key'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_setting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_site_setting_key'))

    op.drop_table('site_setting')
    # ### end Alembic commands ###
